daemon off;
error_log /dev/stderr;
pid /tmp/nginx.pid;

events {}

http {
    include /etc/nginx/mime.types;
    access_log /dev/stdout;

    server {
        listen 80;

        root /app;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
