daemon off;
error_log /dev/stderr;
pid /tmp/nginx.pid;

events {}

http {
    types {
        text/html html htm;
        text/css css;
        application/javascript js mjs;
        application/json json;
        image/svg+xml svg;
        image/avif avif;
        image/webp webp;
        image/png png;
        image/jpeg jpg jpeg;
        font/woff woff;
        font/woff2 woff2;
    }
    default_type application/octet-stream;

    server {
        listen 80;

        root /app;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /vct-ribeirao/ {
            alias /app/;
        }
    }
}
