daemon off;
error_log /dev/stderr;
pid /tmp/nginx.pid;

events {}

http {

    server {
        listen 80;

        root /app;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /vct-ribeirao/ {
            alias /app/;
        }
    }
}
